/* Generated By:JJTree: Do not edit this line. OArraySelector.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

import com.orientechnologies.common.collection.OMultiValue;
import com.orientechnologies.orient.core.command.OCommandContext;
import com.orientechnologies.orient.core.db.record.OIdentifiable;
import com.orientechnologies.orient.core.record.impl.ODocument;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class OArraySelector extends SimpleNode {

  protected ORid              rid;
  protected OInputParameter   inputParam;
  protected OExpression       expression;
  protected OInteger          integer;

  public OArraySelector(int id) {
    super(id);
  }

  public OArraySelector(OrientSql p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(OrientSqlVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public void toString(Map<Object, Object> params, StringBuilder builder) {
    if (rid != null) {
      rid.toString(params, builder);
    } else if (inputParam != null) {
      inputParam.toString(params, builder);
    } else if (expression != null) {
      expression.toString(params, builder);
    } else if (integer != null) {
      integer.toString(params, builder);
    }
  }

    public Object getValue(OIdentifiable iCurrentRecord, Object iResult, OCommandContext ctx) {
      Object key = null;
      if (inputParam!= null) {
        key = inputParam.bindFromInputParams(ctx.getInputParameters());
      } else if (expression != null) {
        key = expression.execute(iCurrentRecord, ctx);
      } else if (integer != null) {
        key = integer;
      }

      if (key == null) {
        return null;
      }
      Object result = getValueFromKey(iResult, ctx, key);
      return result;
  }

  private Object getValueFromKey(Object iResult, OCommandContext ctx, Object key) {
    Object result = null;
    if(iResult instanceof OIdentifiable) {
      result = ((ODocument)((OIdentifiable) iResult).getRecord()).field(key.toString());
    }else if(iResult instanceof Map) {
      result = ((Map) iResult).get(key);
    }else if(OMultiValue.isMultiValue(iResult)) {
      if (key instanceof Number) {
        result = OMultiValue.getValue(iResult, ((Number) key).intValue());
      }else {
        result = getPropertyFromList(iResult, key, ctx);
      }
    }
    return result;
  }

  private Object getPropertyFromList( Object iResult, Object key, OCommandContext ctx) {
    List<Object> result = new ArrayList<Object>();
    for(Object o: OMultiValue.getMultiValueIterable(iResult)){
      result.add(getValueFromKey(iResult, ctx, key ));
    }
    return result;
  }
}
/* JavaCC - OriginalChecksum=f87a5543b1dad0fb5f6828a0663a7c9e (do not edit this line) */
